
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.Timer;



public class frmrail extends javax.swing.JFrame {
    double price,disc,tax,t,netamt,cash,seat;
    boolean btnclick,play;
    Timer tim;
    
    public frmrail() {
        initComponents();
        lblprice.setBackground(new java.awt.Color(0, 0, 0));
        lblprice.setForeground(new java.awt.Color(255, 255, 255));
        lbldisc.setBackground(new java.awt.Color(255, 255, 51));
        lbltax.setBackground(new java.awt.Color(51, 255, 255));
        lblnet.setBackground(new java.awt.Color(250, 7, 7));
        lblnet.setForeground(new java.awt.Color(255, 255, 255));
        lblload.setIcon(new ImageIcon("src\\ajax-loader(1).gif"));
        btntick.setEnabled(false);
        
        tim=new Timer(8000,new ActionListener(){
         public void actionPerformed(ActionEvent evt) {  
           diamsg.pack();
           diamsg.setLocationRelativeTo(null);
           diamsg.setVisible(true);
           diaload.dispose();
           tim.stop();
      } 
    });
    }
    boolean isEmpty() {
        if(optac1.isSelected()==false && optac2.isSelected()==false && optct3.isSelected()==false && optsleeper.isSelected()==false)
           return true;
        else
            return false;
    }
    
    boolean isEmpty2() {
        if(optamerica.isSelected()==false && optcash.isSelected()==false && optmaster.isSelected()==false && optvisa.isSelected()==false)
           return true;
        else
            return false;
    }
    
    public void getPrice() {
        if(optsleeper.isSelected())
            price=1000;
        else if(optct3.isSelected())
            price=1500;
        else if(optac2.isSelected())
            price=2000;
        else
            price=2500;
        lblseat.setText(""+price);
    }
    public void calcBill() {
        cash=netamt=0;
        seat=0;
        try {
            seat=Integer.parseInt(txtseats.getText());
            if(seat<=0) {
                JOptionPane.showMessageDialog(this,"Please Enter Values Of Seat","Error",JOptionPane.ERROR_MESSAGE);
                txtseats.selectAll();
                txtseats.requestFocus();
                seat=0;
            }
            cash=price*seat;
            lblprice.setText("Price Payment ="+cash+"Rs");
            if(disc!=0) {
                netamt=cash-(cash*disc);
                lbldisc.setText("Discount= 2%");
                lbltax.setText("Service Tax= 0%");
                lblnet.setText("Net Payable Amount =" +netamt+"Rs");
            }
            else {
                netamt=cash+(cash*tax);
                lbldisc.setText("Discount= 0%");
                lbltax.setText("Service Tax= 5%");
                lblnet.setText("Net Payable Amount =" +netamt+"Rs");
            }
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Please Don't Leave Seats column Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seat1 = new javax.swing.ButtonGroup();
        pay = new javax.swing.ButtonGroup();
        diaload = new javax.swing.JDialog();
        lblload = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        diamsg = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        optsleeper = new javax.swing.JRadioButton();
        optct3 = new javax.swing.JRadioButton();
        optac2 = new javax.swing.JRadioButton();
        optac1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblseat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        optcash = new javax.swing.JRadioButton();
        optvisa = new javax.swing.JRadioButton();
        optmaster = new javax.swing.JRadioButton();
        optamerica = new javax.swing.JRadioButton();
        btntick = new javax.swing.JButton();
        lblimg2 = new javax.swing.JLabel();
        lblimg1 = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lbldisc = new javax.swing.JLabel();
        lbltax = new javax.swing.JLabel();
        lblnet = new javax.swing.JLabel();
        btndetail = new javax.swing.JButton();

        lblload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblload.setIcon(new ImageIcon("src\\ajax-loader(1).gif"));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Booking....");

        javax.swing.GroupLayout dialoadLayout = new javax.swing.GroupLayout(diaload.getContentPane());
        diaload.getContentPane().setLayout(dialoadLayout);
        dialoadLayout.setHorizontalGroup(
            dialoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialoadLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(lblload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        dialoadLayout.setVerticalGroup(
            dialoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialoadLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblload, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Your Ticket Has Been Booked......");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diamsgLayout = new javax.swing.GroupLayout(diamsg.getContentPane());
        diamsg.getContentPane().setLayout(diamsgLayout);
        diamsgLayout.setHorizontalGroup(
            diamsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diamsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diamsgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        diamsgLayout.setVerticalGroup(
            diamsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diamsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Type Of Seat"));

        seat1.add(optsleeper);
        optsleeper.setText("Sleeper Class");
        optsleeper.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optsleeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat(evt);
            }
        });

        seat1.add(optct3);
        optct3.setText("AC3 Tier");
        optct3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat(evt);
            }
        });

        seat1.add(optac2);
        optac2.setText("AC2 Tier");
        optac2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat(evt);
            }
        });

        seat1.add(optac1);
        optac1.setText("AC1 Tier");
        optac1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat(evt);
            }
        });

        jLabel1.setText("Price Per Seat :-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optsleeper, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optct3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optac2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optac1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblseat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(optsleeper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optct3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optac2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Number Of Seats:-");

        txtseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatsActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Mode Of Payment"));

        pay.add(optcash);
        optcash.setText("Cash");
        optcash.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optcashActionPerformed(evt);
            }
        });

        pay.add(optvisa);
        optvisa.setText("Visa");
        optvisa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optvisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment(evt);
            }
        });

        pay.add(optmaster);
        optmaster.setText("MasterCard");
        optmaster.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment(evt);
            }
        });

        pay.add(optamerica);
        optamerica.setText("AmericanExpress");
        optamerica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeImage(evt);
            }
        });
        optamerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optcash, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optvisa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optmaster, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optamerica, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(optcash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optvisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optmaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optamerica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btntick.setText("Book Ticket");
        btntick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntickActionPerformed(evt);
            }
        });

        lblprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprice.setText("Price In Rs=  0.0");
        lblprice.setOpaque(true);

        lbldisc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldisc.setText(" Discount %= 0.0");
        lbldisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbldisc.setOpaque(true);

        lbltax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltax.setText("Service Tax %= 0.0");
        lbltax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbltax.setOpaque(true);

        lblnet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnet.setText("Net Payable Amount= 0.0 Rs");
        lblnet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblnet.setOpaque(true);

        btndetail.setText("Check Details");
        btndetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtseats))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btndetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(btntick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblimg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnet, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndetail)
                        .addGap(12, 12, 12)
                        .addComponent(btntick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblprice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltax)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeImage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeImage
        JRadioButton optButton =(JRadioButton) evt.getSource();
        if(optButton==optsleeper)
            lblimg1.setIcon(new ImageIcon("src\\Project\\2Q==(2).jpg"));
        else if(optButton==optct3)
            lblimg1.setIcon(new ImageIcon("src\\Project\\train3.jpg"));
        else if(optButton==optac2)
            lblimg1.setIcon(new ImageIcon("src\\Project\\2Q==(3).jpg"));
        else if(optButton==optac1)
            lblimg1.setIcon(new ImageIcon("src\\Project\\2Q==(1).jpg"));
        else if(optButton==optcash)
            lblimg2.setIcon(new ImageIcon("src\\Project\\donkey.png"));
        else if(optButton==optvisa)
            lblimg2.setIcon(new ImageIcon("src\\Project\\k7wlEv0H1UigUYecW3AAAAAASUVORK5CYII=.jpg"));
        else if(optButton==optmaster)
            lblimg2.setIcon(new ImageIcon("src\\Project\\gs0 J7C0tExqgAAAABJRU5ErkJggg==.jpg"));
        else
            lblimg2.setIcon(new ImageIcon("src\\Project\\2Q==w.png"));
    }//GEN-LAST:event_ChangeImage

    private void btntickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntickActionPerformed
       diaload.pack();
       diaload.setLocationRelativeTo(this);
       diaload.setVisible(true);
       if(!play)
          tim.start();
    }//GEN-LAST:event_btntickActionPerformed

    private void Seat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat
        getPrice();
        if(btnclick)
            calcBill();
    }//GEN-LAST:event_Seat

    private void optcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optcashActionPerformed
        if(isEmpty() || isEmpty2()) 
        {
            JOptionPane.showMessageDialog(this,"Please Select Seat Type First","Error",JOptionPane.ERROR_MESSAGE);
            disc=0.02;
            tax=0.00;  
            lbldisc.setText("Discount%=2");
            lblprice.setText("Price in Rs=____");
            lblnet.setText("Net Payable Amount=____Rs");
            lbltax.setText("Servive Tax%=00");
            txtseats.setText("");
            txtseats.requestFocus();
        }
        else {
            disc=0.02;
            tax=0.00;  
            lbldisc.setText("Discount%=2");
            lblprice.setText("Price in Rs=____");
            lblnet.setText("Net Payable Amount=____Rs");
            lbltax.setText("Servive Tax%=00");
            if(btnclick)
                calcBill();
       }
    }//GEN-LAST:event_optcashActionPerformed

    private void payment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment
        
        if(isEmpty() || isEmpty2()) {
            JOptionPane.showMessageDialog(this,"Please Select Seat Type First","Error",JOptionPane.ERROR_MESSAGE);
            disc=0.00;
            tax=0.05;
            lbldisc.setText("Discount%=0.0");
            lblprice.setText("Price in Rs=____");
            lblnet.setText("Net Payable Amount=____Rs");
            lbltax.setText("Servive Tax%=5");
            txtseats.setText("");
            txtseats.requestFocus();
        }
        else
        {
            disc=0.00;
            tax=0.05;
            lbldisc.setText("Discount%=0.0");
            lblprice.setText("Price in Rs=____");
            lblnet.setText("Net Payable Amount=____Rs");
            lbltax.setText("Servive Tax%=5");
            if(btnclick)
                calcBill();
        }
    }//GEN-LAST:event_payment

    private void btndetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailActionPerformed
        if(isEmpty() || isEmpty2())
            JOptionPane.showMessageDialog(this,"Please Select A Option","Error",JOptionPane.ERROR_MESSAGE);
        else {
            calcBill();
            btnclick=true;
            btntick.setEnabled(true);
        }   
    }//GEN-LAST:event_btndetailActionPerformed

    private void txtseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatsActionPerformed
        if(btnclick)
            calcBill();
    }//GEN-LAST:event_txtseatsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmrail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndetail;
    private javax.swing.JButton btntick;
    private javax.swing.JDialog diaload;
    private javax.swing.JDialog diamsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldisc;
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JLabel lblload;
    private javax.swing.JLabel lblnet;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblseat;
    private javax.swing.JLabel lbltax;
    private javax.swing.JRadioButton optac1;
    private javax.swing.JRadioButton optac2;
    private javax.swing.JRadioButton optamerica;
    private javax.swing.JRadioButton optcash;
    private javax.swing.JRadioButton optct3;
    private javax.swing.JRadioButton optmaster;
    private javax.swing.JRadioButton optsleeper;
    private javax.swing.JRadioButton optvisa;
    private javax.swing.ButtonGroup pay;
    private javax.swing.ButtonGroup seat1;
    private javax.swing.JTextField txtseats;
    // End of variables declaration//GEN-END:variables
}
