import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * employee_details.java
 *
 * Created on Dec 25, 2011, 4:29:52 PM
 */

/**
 *
 * @author RAJESH HUMAR
 */
public class employee_details extends javax.swing.JFrame {

    /** Creates new form employee_details */
    public employee_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        displayrecords = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        removerec = new javax.swing.JButton();
        addrec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee's Record");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("EMPLOYEE DETAILS");

        displayrecords.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayrecords.setForeground(new java.awt.Color(0, 204, 0));
        displayrecords.setText("DISPLAY RECORDS");
        displayrecords.setToolTipText("CLICK TO DISPLAY RECORDS OF EMPLOYEES...");
        displayrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayrecordsActionPerformed(evt);
            }
        });

        signout.setFont(new java.awt.Font("Tahoma", 1, 14));
        signout.setForeground(new java.awt.Color(0, 102, 102));
        signout.setText("SIGNOUT");
        signout.setToolTipText("CLICK TO SIGNOUT...");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });

        removerec.setFont(new java.awt.Font("Tahoma", 1, 14));
        removerec.setForeground(new java.awt.Color(204, 0, 204));
        removerec.setText("REMOVE REC.");
        removerec.setToolTipText("CLICK TO REMOVE EMPLOYEE.... ");
        removerec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerecActionPerformed(evt);
            }
        });

        addrec.setFont(new java.awt.Font("Tahoma", 1, 14));
        addrec.setForeground(new java.awt.Color(204, 0, 204));
        addrec.setText("ADD NEW REC.");
        addrec.setToolTipText("CLICK TO ADD EMPLOYEE...");
        addrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPCODE", "NAME", "ADDRESS", "CONTACT NO."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addrec)
                                .addGap(41, 41, 41)
                                .addComponent(removerec, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(signout)
                                .addGap(38, 38, 38))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(displayrecords, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayrecords, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerec, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayrecordsActionPerformed
    DefaultTableModel tab = (DefaultTableModel) table.getModel();
try{
Class.forName("com.mysql.jdbc.Driver");
        String DB="jdbc:mysql://localhost/board_project";
        Connection con=DriverManager.getConnection(DB,"root","kvuc");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from emp;" );
String n,d,c,e;
while (rs.next())
{
n= rs.getString(1);
d= rs.getString(2);
c= rs.getString(3);
e= rs.getString(4);
Object rec[]={n,d,c,e};
tab.addRow(rec);
}
rs.close();
stmt.close();
con.close();
}
catch (Exception e)
{ JOptionPane.showMessageDialog(null, e.getMessage() ); }        // TODO add your handling code here:
    }//GEN-LAST:event_displayrecordsActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
this.dispose();
new login().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_signoutActionPerformed

    private void removerecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerecActionPerformed
        new delete().setVisible(true);
 new delete().getAlignmentX();  // TODO add your handling code here:
}//GEN-LAST:event_removerecActionPerformed

    private void addrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecActionPerformed
    new addemployee().setVisible(true);
    new addemployee().getAlignmentX();// TODO add your handling code here:
    }//GEN-LAST:event_addrecActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrec;
    private javax.swing.JButton displayrecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerec;
    private javax.swing.JButton signout;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
