/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f1.java
 *
 * Created on Dec 25, 2011, 4:05:57 PM
 */

/**
 *
 * @author RAJESH HUMAR
 */
public class f1 extends javax.swing.JFrame {

    /** Creates new form f1 */
    public f1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mlist = new javax.swing.JMenu();
        availablelist = new javax.swing.JMenu();
        pcgames = new javax.swing.JMenuItem();
        movies = new javax.swing.JMenuItem();
        albums = new javax.swing.JMenuItem();
        memlist = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        issued = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        aboutus = new javax.swing.JMenuItem();
        developer = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Form");
        setBackground(new java.awt.Color(0, 204, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("WELCOME TO UNIQUE CD & DVD library");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        jLabel1.setFocusCycleRoot(true);

        login1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        login1.setForeground(new java.awt.Color(0, 255, 204));
        login1.setText("LOGIN ");
        login1.setToolTipText("TO CONTINUE click here !!!");
        login1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("EXIT");
        exit.setToolTipText("CLICK HERE TO EXIT!!!!!");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\HCL\\Desktop\\main.PNG")); // NOI18N

        jMenuBar1.setForeground(new java.awt.Color(255, 204, 204));

        mlist.setBackground(new java.awt.Color(204, 255, 204));
        mlist.setForeground(new java.awt.Color(255, 0, 0));
        mlist.setText("REPORT");
        mlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlistActionPerformed(evt);
            }
        });

        availablelist.setBackground(new java.awt.Color(204, 204, 255));
        availablelist.setForeground(new java.awt.Color(255, 0, 0));
        availablelist.setText("AVAILABLE CDs & DVDs ");
        availablelist.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                availablelistFocusGained(evt);
            }
        });

        pcgames.setBackground(new java.awt.Color(204, 255, 204));
        pcgames.setText("P C GAMES");
        pcgames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcgamesActionPerformed(evt);
            }
        });
        availablelist.add(pcgames);

        movies.setBackground(new java.awt.Color(204, 255, 204));
        movies.setText("MOVIES");
        movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesActionPerformed(evt);
            }
        });
        movies.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                moviesFocusGained(evt);
            }
        });
        availablelist.add(movies);

        albums.setBackground(new java.awt.Color(204, 255, 204));
        albums.setText("ALBUMS");
        albums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumsActionPerformed(evt);
            }
        });
        availablelist.add(albums);

        mlist.add(availablelist);

        memlist.setBackground(new java.awt.Color(204, 204, 255));
        memlist.setFont(new java.awt.Font("Tahoma", 1, 11));
        memlist.setForeground(new java.awt.Color(0, 255, 204));
        memlist.setText("MEMBER LIST");
        memlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memlistActionPerformed(evt);
            }
        });
        mlist.add(memlist);

        jMenuBar1.add(mlist);

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setForeground(new java.awt.Color(255, 0, 0));
        jMenu1.setText("CDs & DVDs");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        issued.setBackground(new java.awt.Color(255, 204, 204));
        issued.setForeground(new java.awt.Color(0, 204, 204));
        issued.setText("issued cd & dvds");
        issued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedActionPerformed(evt);
            }
        });
        jMenu1.add(issued);

        jMenuBar1.add(jMenu1);

        about.setBackground(new java.awt.Color(255, 204, 204));
        about.setForeground(new java.awt.Color(255, 0, 51));
        about.setText("ABOUT US");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        aboutus.setBackground(new java.awt.Color(204, 255, 204));
        aboutus.setText("about us");
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        about.add(aboutus);

        developer.setBackground(new java.awt.Color(204, 255, 204));
        developer.setText("about developer");
        developer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                developerActionPerformed(evt);
            }
        });
        about.add(developer);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
 new login().setVisible(true);
 new login().getAlignmentX();
 // TODO add your handling code here:
    }//GEN-LAST:event_login1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void moviesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moviesFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_moviesFocusGained

    private void pcgamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcgamesActionPerformed
     new pcgameslist().setVisible(true);   // TODO add your handling code here:
}//GEN-LAST:event_pcgamesActionPerformed

    private void moviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesActionPerformed
       new movieslist().setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_moviesActionPerformed

    private void albumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumsActionPerformed
        new albumslist().setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_albumsActionPerformed

    private void availablelistFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_availablelistFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_availablelistFocusGained

    private void memlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memlistActionPerformed
         new mlist().setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_memlistActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void issuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedActionPerformed
       new illist().setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_issuedActionPerformed

    private void mlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlistActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_mlistActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
  // TODO add your handling code here:
}//GEN-LAST:event_aboutActionPerformed

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
      new aboutus().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusActionPerformed

    private void developerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_developerActionPerformed
new developer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_developerActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem aboutus;
    private javax.swing.JMenuItem albums;
    private javax.swing.JMenu availablelist;
    private javax.swing.JMenuItem developer;
    private javax.swing.JButton exit;
    private javax.swing.JMenuItem issued;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton login1;
    private javax.swing.JMenuItem memlist;
    private javax.swing.JMenu mlist;
    private javax.swing.JMenuItem movies;
    private javax.swing.JMenuItem pcgames;
    // End of variables declaration//GEN-END:variables

}
