import java.sql.*;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Dec 26, 2011, 9:52:43 PM
 */

/**
 *
 * @author RAJESH HUMAR
 */
public class login extends javax.swing.JFrame {
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
String DB="jdbc:mysql://localhost/board_project";
    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lt1 = new javax.swing.JTextField();
        lp1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        rdmanager = new javax.swing.JRadioButton();
        rdemployee = new javax.swing.JRadioButton();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("LOGIN HERE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("USER NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("PASSWORD");

        lt1.setFont(new java.awt.Font("Tahoma", 1, 14));
        lt1.setToolTipText("INSERT USER NAME HERE...");

        lp1.setFont(new java.awt.Font("Tahoma", 1, 14));
        lp1.setToolTipText("INSERT PASSWORD HERE...");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setName("Select your Status"); // NOI18N

        buttonGroup1.add(rdmanager);
        rdmanager.setFont(new java.awt.Font("Tahoma", 1, 14));
        rdmanager.setForeground(new java.awt.Color(51, 255, 255));
        rdmanager.setText("MANAGER");

        buttonGroup1.add(rdemployee);
        rdemployee.setFont(new java.awt.Font("Tahoma", 1, 14));
        rdemployee.setForeground(new java.awt.Color(0, 204, 204));
        rdemployee.setText("EMPLOYEE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdmanager)
                    .addComponent(rdemployee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(rdmanager)
                .addGap(46, 46, 46)
                .addComponent(rdemployee)
                .addGap(22, 22, 22))
        );

        login.setBackground(new java.awt.Color(255, 204, 204));
        login.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(51, 255, 0));
        login.setText("LOGIN");
        login.setToolTipText("CLICK HERE TO LOGIN!!!!");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 204, 204));
        back.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(153, 0, 153));
        back.setText("BACK");
        back.setToolTipText("GO BACK.....");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59)
                                .addComponent(lt1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61)
                                .addComponent(lp1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
if(rdmanager.isSelected()){
  String usrid1 = lt1.getText();
try{
Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/board_project","root","kvuc");
        stmt = con.createStatement();
        rs = stmt.executeQuery("select passwrd from login_info where userid ='"+usrid1+"';" );

  String pswrd = new String(lp1.getPassword());
  rs.next();
  String psword= rs.getString(1);
if (pswrd.equals(psword)){
  new employee_details().setVisible(true);
  
}
else
    JOptionPane.showMessageDialog(this,"Invalid user name , password");
lt1.setText("");
lp1.setText("");
rs.close();
stmt.close();
con.close();
}
catch (Exception e)
{ JOptionPane.showMessageDialog(null, e.getMessage()+"error in connection" ); }
}
else
if(rdemployee.isSelected()){
       String usrid1 = lt1.getText();
try{
Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/board_project","root","kvuc");
        stmt = con.createStatement();
        rs = stmt.executeQuery("select password from elogin_info where username ='"+usrid1+"';" );

  String pswrd = new String(lp1.getPassword());
  rs.next();
  String psword= rs.getString(1);
if (pswrd.equals(psword)){
  new deal().setVisible(true);

}
else
    JOptionPane.showMessageDialog(this,"Invalid user name , password");
lt1.setText("");
lp1.setText("");
rs.close();
stmt.close();
con.close();
}
catch (Exception e)
{ JOptionPane.showMessageDialog(null, e.getMessage()+"error in connection" ); }
    }// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField lp1;
    private javax.swing.JTextField lt1;
    private javax.swing.JRadioButton rdemployee;
    private javax.swing.JRadioButton rdmanager;
    // End of variables declaration//GEN-END:variables

}
