/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * user2form.java
 *
 * Created on Jan 6, 2006, 5:58:14 PM
 */

/**
 *
 * @author ARJUN
 */
public class MAINFORM extends javax.swing.JFrame {

    /** Creates new form user2form */
    public MAINFORM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ABOUTUS = new javax.swing.JMenu();
        TOTALVEH = new javax.swing.JMenuItem();
        VEHRECNAV = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        DELETION = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        TYPECON = new javax.swing.JMenuItem();
        TYPEMOD = new javax.swing.JMenuItem();
        TYPEDEL = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        TYPEAVA = new javax.swing.JMenuItem();
        VEHCLES = new javax.swing.JMenu();
        VEHCONSOLE = new javax.swing.JMenuItem();
        MOD = new javax.swing.JMenuItem();
        DEL = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ISSUE = new javax.swing.JMenuItem();
        RETURN = new javax.swing.JMenuItem();
        REPORT = new javax.swing.JMenu();
        ONBOOK = new javax.swing.JMenuItem();
        AVAILABLE = new javax.swing.JMenuItem();
        MEMBER = new javax.swing.JMenu();
        MAINMEMCON = new javax.swing.JMenuItem();
        MMDEL = new javax.swing.JMenuItem();
        MMEMMOD = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MAINMEMBERSRECNAV = new javax.swing.JMenuItem();
        MMLIST = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MEMBERSRECNAV = new javax.swing.JMenuItem();
        MMOD = new javax.swing.JMenuItem();
        MDEL = new javax.swing.JMenuItem();
        MLIST = new javax.swing.JMenuItem();
        TRANSACTION = new javax.swing.JMenu();
        BOOKVEH = new javax.swing.JMenuItem();
        RETURNVEH = new javax.swing.JMenuItem();
        MAINPAGE = new javax.swing.JMenu();
        MAINPAGEGO = new javax.swing.JMenuItem();
        QUIT = new javax.swing.JMenu();
        QUITAPP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 48));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("OHM TRAVEL AGENCY");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/17.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        ABOUTUS.setBorder(new javax.swing.border.MatteBorder(null));
        ABOUTUS.setText("ABOUT US");

        TOTALVEH.setText("TOTAL VEHICLES D");
        TOTALVEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALVEHActionPerformed(evt);
            }
        });
        ABOUTUS.add(TOTALVEH);

        VEHRECNAV.setText("VEH RECORD NAVIGATION D");
        VEHRECNAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEHRECNAVActionPerformed(evt);
            }
        });
        ABOUTUS.add(VEHRECNAV);
        ABOUTUS.add(jSeparator5);

        jMenuItem1.setText("MODIFICATION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ABOUTUS.add(jMenuItem1);

        DELETION.setText("DELETION D");
        DELETION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETIONActionPerformed(evt);
            }
        });
        ABOUTUS.add(DELETION);
        ABOUTUS.add(jSeparator6);

        TYPECON.setText("TYPE CONSOLE");
        TYPECON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYPECONActionPerformed(evt);
            }
        });
        ABOUTUS.add(TYPECON);

        TYPEMOD.setText("TYPE UPDATION");
        TYPEMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYPEMODActionPerformed(evt);
            }
        });
        ABOUTUS.add(TYPEMOD);

        TYPEDEL.setText("TYPE DELETION");
        TYPEDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYPEDELActionPerformed(evt);
            }
        });
        ABOUTUS.add(TYPEDEL);
        ABOUTUS.add(jSeparator7);

        TYPEAVA.setText("VEHICLE TYPE AVAILABLE D");
        TYPEAVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYPEAVAActionPerformed(evt);
            }
        });
        ABOUTUS.add(TYPEAVA);

        jMenuBar1.add(ABOUTUS);

        VEHCLES.setBorder(new javax.swing.border.MatteBorder(null));
        VEHCLES.setText("     VIEHCLES    ");

        VEHCONSOLE.setText("VEHICLE COSOLE D");
        VEHCONSOLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEHCONSOLEActionPerformed(evt);
            }
        });
        VEHCLES.add(VEHCONSOLE);

        MOD.setText("MODIFICATION D");
        MOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODActionPerformed1(evt);
            }
        });
        VEHCLES.add(MOD);

        DEL.setText("DELETION D");
        DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELActionPerformed(evt);
            }
        });
        VEHCLES.add(DEL);
        VEHCLES.add(jSeparator2);

        ISSUE.setText("ISSUE VEHICLE D");
        ISSUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSUEActionPerformed(evt);
            }
        });
        VEHCLES.add(ISSUE);

        RETURN.setText("RETURN VEHICLE D");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });
        VEHCLES.add(RETURN);

        jMenuBar1.add(VEHCLES);

        REPORT.setBorder(new javax.swing.border.MatteBorder(null));
        REPORT.setText("REPORT");

        ONBOOK.setText("ON BOOKING  ");
        ONBOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONBOOKActionPerformed(evt);
            }
        });
        REPORT.add(ONBOOK);

        AVAILABLE.setText("AVAILABLE ");
        AVAILABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVAILABLEActionPerformed(evt);
            }
        });
        REPORT.add(AVAILABLE);

        jMenuBar1.add(REPORT);

        MEMBER.setBorder(new javax.swing.border.MatteBorder(null));
        MEMBER.setText("    MEMBERS");
        MEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMBERActionPerformed(evt);
            }
        });

        MAINMEMCON.setText("MAIN MEMBER CONSOLE");
        MAINMEMCON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAINMEMCONActionPerformed(evt);
            }
        });
        MEMBER.add(MAINMEMCON);

        MMDEL.setText("MAIN MEMBERS DELETION D");
        MMDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMDELActionPerformed(evt);
            }
        });
        MEMBER.add(MMDEL);

        MMEMMOD.setText("MAIN MEMBER MODIFICATION D");
        MMEMMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMEMMODActionPerformed(evt);
            }
        });
        MEMBER.add(MMEMMOD);
        MEMBER.add(jSeparator3);

        MAINMEMBERSRECNAV.setText("MAINMEMBERS  RECORD NEVIGATION ");
        MAINMEMBERSRECNAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAINMEMBERSRECNAVActionPerformed1(evt);
            }
        });
        MEMBER.add(MAINMEMBERSRECNAV);

        MMLIST.setText("MAIN MEMBERS LIST");
        MMLIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMLISTActionPerformed(evt);
            }
        });
        MEMBER.add(MMLIST);
        MEMBER.add(jSeparator4);

        MEMBERSRECNAV.setText("MEMBERS USING SERVICES RECORD NEVIGATION ");
        MEMBERSRECNAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMBERSRECNAVActionPerformed(evt);
            }
        });
        MEMBER.add(MEMBERSRECNAV);

        MMOD.setText("MEMBER USING SERVICES UPDATION");
        MMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMODActionPerformed(evt);
            }
        });
        MEMBER.add(MMOD);

        MDEL.setText("MEMBERS USING SERVICE DELETION D");
        MDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDELActionPerformed(evt);
            }
        });
        MEMBER.add(MDEL);

        MLIST.setText("MEMBERS USING SERVICES LIST");
        MLIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLISTActionPerformed(evt);
            }
        });
        MEMBER.add(MLIST);

        jMenuBar1.add(MEMBER);

        BOOKVEH.setText("BOOK VEHICLE");
        TRANSACTION.add(BOOKVEH);

        RETURNVEH.setText("RETURN VEHICLE");
        TRANSACTION.add(RETURNVEH);

        jMenuBar1.add(TRANSACTION);

        MAINPAGE.setBorder(new javax.swing.border.MatteBorder(null));
        MAINPAGE.setText("     FOR GOING TOMAIN PAGE");

        MAINPAGEGO.setText(" WANT TO GO TO MAIN PAGE CLICK HERE D");
        MAINPAGEGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAINPAGEGOActionPerformed(evt);
            }
        });
        MAINPAGE.add(MAINPAGEGO);

        jMenuBar1.add(MAINPAGE);

        QUIT.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        QUIT.setText("EXIT");

        QUITAPP.setText("QUIT APPLICATION");
        QUITAPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUITAPPActionPerformed(evt);
            }
        });
        QUIT.add(QUITAPP);

        jMenuBar1.add(QUIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        new vehmod().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem13ActionPerformed

    private void MAINPAGEGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAINPAGEGOActionPerformed
    new mainpage().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_MAINPAGEGOActionPerformed

    private void QUITAPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUITAPPActionPerformed
     System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_QUITAPPActionPerformed

    private void VEHCONSOLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEHCONSOLEActionPerformed
 new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_VEHCONSOLEActionPerformed

    private void MODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODActionPerformed

    private void MODActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODActionPerformed1
 new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_MODActionPerformed1

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
   new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_DELActionPerformed

    private void ISSUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSUEActionPerformed
         new Issueveh().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ISSUEActionPerformed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        new Returnveh().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_RETURNActionPerformed

    private void MAINMEMBERSRECNAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAINMEMBERSRECNAVActionPerformed
          new MAINMEMBNAV().setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_MAINMEMBERSRECNAVActionPerformed

    private void MEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMBERActionPerformed
       new MEMBNAV().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_MEMBERActionPerformed

    private void MMMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMMODActionPerformed
         new MainMembmod().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_MMMODActionPerformed

    private void MMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMODActionPerformed
       new Membmod().setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_MMODActionPerformed

    private void MDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDELActionPerformed
        new MembDel().setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_MDELActionPerformed

    private void MEMBERSRECNAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMBERSRECNAVActionPerformed
    new MEMBNAV().setVisible(true);
        this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_MEMBERSRECNAVActionPerformed

    private void TYPEAVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYPEAVAActionPerformed
        new TYPE_V().setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
}//GEN-LAST:event_TYPEAVAActionPerformed

    private void MODIFICATIONActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICATIONActionPerformed1
   
        // TODO add your handling code here:
}//GEN-LAST:event_MODIFICATIONActionPerformed1

    private void TOTALVEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALVEHActionPerformed

        new TVEH().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_TOTALVEHActionPerformed

    private void VEHRECNAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEHRECNAVActionPerformed
   new vehrecnav().setVisible(true);
        this.setVisible(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_VEHRECNAVActionPerformed

    private void MMDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMDELActionPerformed
       new PASSWORDFEILD2().setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
}//GEN-LAST:event_MMDELActionPerformed

    private void MAINMEMCONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAINMEMCONActionPerformed
       new PASSWORDFEILD2().setVisible(true);
        this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_MAINMEMCONActionPerformed

    private void MAINMEMBERSRECNAVActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAINMEMBERSRECNAVActionPerformed1
      new MAINMEMBNAV().setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_MAINMEMBERSRECNAVActionPerformed1

    private void MMEMMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMEMMODActionPerformed
      new PASSWORDFEILD2().setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_MMEMMODActionPerformed

    private void TYPEMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYPEMODActionPerformed
        new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_TYPEMODActionPerformed

    private void TYPEDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYPEDELActionPerformed
       new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_TYPEDELActionPerformed

    private void TYPECONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYPECONActionPerformed
       new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_TYPECONActionPerformed

    private void MLISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLISTActionPerformed
      new MList().setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_MLISTActionPerformed

    private void DELETIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETIONActionPerformed
        new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_DELETIONActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        new PASSWORDFEILD1().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MMLISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMLISTActionPerformed
        new MMList().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
}//GEN-LAST:event_MMLISTActionPerformed

    private void AVAILABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVAILABLEActionPerformed

        new avilableveh().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_AVAILABLEActionPerformed

    private void ONBOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONBOOKActionPerformed
        new ONBOOK().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_ONBOOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ABOUTUS;
    private javax.swing.JMenuItem AVAILABLE;
    private javax.swing.JMenuItem BOOKVEH;
    private javax.swing.JMenuItem DEL;
    private javax.swing.JMenuItem DELETION;
    private javax.swing.JMenuItem ISSUE;
    private javax.swing.JMenuItem MAINMEMBERSRECNAV;
    private javax.swing.JMenuItem MAINMEMCON;
    private javax.swing.JMenu MAINPAGE;
    private javax.swing.JMenuItem MAINPAGEGO;
    private javax.swing.JMenuItem MDEL;
    private javax.swing.JMenu MEMBER;
    private javax.swing.JMenuItem MEMBERSRECNAV;
    private javax.swing.JMenuItem MLIST;
    private javax.swing.JMenuItem MMDEL;
    private javax.swing.JMenuItem MMEMMOD;
    private javax.swing.JMenuItem MMLIST;
    private javax.swing.JMenuItem MMOD;
    private javax.swing.JMenuItem MOD;
    private javax.swing.JMenuItem ONBOOK;
    private javax.swing.JMenu QUIT;
    private javax.swing.JMenuItem QUITAPP;
    private javax.swing.JMenu REPORT;
    private javax.swing.JMenuItem RETURN;
    private javax.swing.JMenuItem RETURNVEH;
    private javax.swing.JMenuItem TOTALVEH;
    private javax.swing.JMenu TRANSACTION;
    private javax.swing.JMenuItem TYPEAVA;
    private javax.swing.JMenuItem TYPECON;
    private javax.swing.JMenuItem TYPEDEL;
    private javax.swing.JMenuItem TYPEMOD;
    private javax.swing.JMenu VEHCLES;
    private javax.swing.JMenuItem VEHCONSOLE;
    private javax.swing.JMenuItem VEHRECNAV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables

}
